//HISTORY:
export const FETCH_HISTORY_START = 'FETCH_HISTORY_START';
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';

//MATCH DETAILS:
export const FETCH_MATCH_DETAILS_START = 'FETCH_MATCH_DETAILS_START';
export const FETCH_MATCH_DETAILS_FAIL = 'FETCH_MATCH_DETAILS_FAIL';
export const FETCH_MATCH_DETAILS_SUCCESS = 'FETCH_MATCH_DETAILS_SUCCESS';
